# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='numOfNews',
            field=models.TextField(),
        ),
    ]
