# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20170203_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='relatedKeys',
            field=models.TextField(blank=True, null=True),
        ),
    ]
