# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20170208_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='donut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
